

#timeout: 10
#

# default destination
# when no SNI name found 
# or parse TLS HELLO message failed
default: 127.0.0.1:8443

# the port listen on
# can specify multiple ports
listen:
    - 443

# forward rules
# exact match or wildcard match
forward_rules:
    "*:443": "*:443"
